print('Welcome, please Enter The Following:')
print()
adjective = input('Enter an adjective:')
print()
animal = input('Enter any animal:')
print()
verb = input('Enter a verb:')
print()
exclamation = input('Enter an exclamation:')
print()
verb2 = input('Enter a verb: ')
print()
verb3 = input('Enter a verb: ')
print()
verb4 = input('Enter a verb: ')
print()
print(f'The other day, I was really in trouble.')
print() 
print(f'It all started when I saw a very {adjective}')
print() 
print(f'{animal} down the hallway. "{exclamation.capitalize()}!" I yelled.')
print() 
print(f'But all I could think to do was to {verb} over and over.')
print() 
print(f'Miraculously, that caused it to stop, but not before it tried to {verb2} right in front of my family.')
print()
print(f'And we {verb4} over it.')
input()